# Generated by Django 4.1.3 on 2022-11-02 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionDropdown',
            fields=[
                ('sno', models.AutoField(db_column='Sno', primary_key=True, serialize=False)),
                ('pid', models.IntegerField(blank=True, db_column='Pid', null=True)),
                ('field', models.CharField(blank=True, db_column='Field', max_length=255, null=True)),
                ('value', models.CharField(blank=True, db_column='Value', max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ElectionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description_language', models.JSONField(default=dict)),
                ('phases', models.IntegerField()),
                ('election_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.electiondropdown')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ElectionPhaseWiseState_2022',
            fields=[
                ('uid', models.IntegerField(db_column='Uid', primary_key=True, serialize=False)),
                ('phase', models.CharField(max_length=4)),
                ('state', models.CharField(max_length=255)),
                ('election_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.electioninfo')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Electiontiming',
            fields=[
                ('uid', models.IntegerField(db_column='Uid', primary_key=True, serialize=False)),
                ('session', models.CharField(blank=True, max_length=16, null=True)),
                ('session_name', models.CharField(max_length=8)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ElectionStateWiseConsituency_2022',
            fields=[
                ('uid', models.IntegerField(db_column='Uid', primary_key=True, serialize=False)),
                ('constituency', models.CharField(max_length=255)),
                ('phase_stateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.electionphasewisestate_2022')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ElectionLockingUnlocking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_type', models.CharField(max_length=8)),
                ('unlock_from', models.DateTimeField(default=None, null=True)),
                ('unlock_to', models.DateTimeField(default=None, null=True)),
                ('status', models.CharField(db_column='status', default='INSERT', max_length=16)),
                ('created_at', models.DateTimeField(auto_now=True, db_column='created_at')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.electiontiming')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='electioninfo',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.electiontiming'),
        ),
    ]
