# Generated by Django 3.2 on 2022-12-12 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '__first__'),
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionCandidates_2022',
            fields=[
                ('id', models.AutoField(db_column='Uid', primary_key=True, serialize=False)),
                ('is_Indian', models.BooleanField(default=True)),
                ('qualification', models.JSONField(default=dict)),
                ('candidate_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.userprofile')),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.electionstatewiseconsituency_2022')),
                ('election_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='election.electioninfo')),
                ('party', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='ElectionParty_2022', to='election.electiondropdown')),
                ('religion', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='ElectionReligion_2022', to='election.electiondropdown')),
                ('session', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='election.electiontiming')),
            ],
        ),
    ]
