# Generated by Django 3.2 on 2022-11-04 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_officialsdetails_useraddress_userprofile'),
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electioninfo',
            name='added_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.officialsdetails'),
        ),
        migrations.AddField(
            model_name='electioninfo',
            name='status',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='electionlockingunlocking',
            name='unlocked_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.officialsdetails'),
        ),
    ]
