# Generated by Django 3.2 on 2022-12-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electioncandidates_2022',
            name='status',
            field=models.CharField(blank=True, default='INSERT', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='electionlockingunlocking_2022',
            name='status',
            field=models.CharField(blank=True, default='INSERT', max_length=16, null=True),
        ),
    ]
