# Generated by Django 3.2 on 2022-12-12 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_electioncandidates_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electioncandidates_2022',
            name='election_id',
        ),
    ]
