# Generated by Django 3.2 on 2022-11-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_auto_20221104_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='electioninfo',
            name='current_status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
