# Generated by Django 3.2 on 2022-11-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_electioninfo_current_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionphasewisestate_2022',
            name='phase',
            field=models.CharField(max_length=16),
        ),
    ]
