# Generated by Django 3.2 on 2022-11-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_alter_electionphasewisestate_2022_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionphasewisestate_2022',
            name='uid',
            field=models.AutoField(db_column='Uid', primary_key=True, serialize=False),
        ),
    ]
