# Generated by Django 3.2 on 2022-11-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_alter_electionphasewisestate_2022_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionstatewiseconsituency_2022',
            name='uid',
            field=models.AutoField(db_column='Uid', primary_key=True, serialize=False),
        ),
    ]
