# Generated by Django 3.2 on 2022-11-24 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20221104_0743'),
        ('election', '0006_alter_electionstatewiseconsituency_2022_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionRolesAssigned_2022',
            fields=[
                ('uid', models.AutoField(db_column='Uid', primary_key=True, serialize=False)),
                ('assigned_to', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.officialsdetails')),
                ('constituency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.electionstatewiseconsituency_2022')),
                ('election_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.electioninfo')),
                ('phase_stateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.electionphasewisestate_2022')),
                ('roles', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.electiondropdown')),
            ],
        ),
    ]
