# Generated by Django 3.2 on 2022-11-29 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0007_electionrolesassigned_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electionrolesassigned_2022',
            options={'managed': True},
        ),
        migrations.CreateModel(
            name='ElectionLockingUnlocking_2022',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=8)),
                ('startDate', models.DateTimeField(default=None, null=True)),
                ('endDate', models.DateTimeField(default=None, null=True)),
                ('electionName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.electioninfo')),
                ('lockType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.electiondropdown')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
