# Generated by Django 3.2 on 2022-12-06 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeftPanel',
            fields=[
                ('sno', models.AutoField(db_column='Sno', primary_key=True, serialize=False)),
                ('pid', models.IntegerField(blank=True, db_column='Pid', null=True)),
                ('name', models.CharField(default=None, max_length=512)),
                ('route', models.CharField(default=None, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.leftpanel')),
                ('official', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.officialsdetails')),
            ],
        ),
    ]
