# Generated by Django 3.2 on 2022-11-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='Admin', max_length=16),
            preserve_default=False,
        ),
    ]
